---
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: main.go
    ldflags:
      - "-X github.com/veerendra2/gopackages/version.Version={{.Version}}"
      - "-X github.com/veerendra2/gopackages/version.Revision={{.Commit}}"
      - "-X github.com/veerendra2/gopackages/version.Branch={{.Branch}}"
      - "-X github.com/veerendra2/gopackages/version.BuildUser={{.Env.USER}}"
      - "-X github.com/veerendra2/gopackages/version.BuildDate={{.Date}}"

archives:
  - formats: ["zip"]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

homebrew_casks:
  - name: cold2warm
    directory: Casks
    homepage: "https://github.com/veerendra2/cold2warm"
    description: "A CLI tool to bulk-restore S3 objects from archival storage classes using concurrent goroutines."
    url:
      verified: github.com/veerendra2/cold2warm
      template: "https://github.com/veerendra2/cold2warm/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    hooks:
      post:
        install: |
          if OS.mac?
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/quotations"]
          end
    repository:
      owner: veerendra2
      name: homebrew-tap
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
